### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'elm-oracle'

### ISSUE THREAD

**Issue by simonewebdesign** [ElmCast/elm-oracle#15]
Not sure why this happens. Basically when I open Sublime Text for the first time it works. But then when I open it again (usually with `subl .`) and I open a `.elm` file, this is what I get in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/simone/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 226, in on_activated_async
    view_load(view)
  File "/Users/simone/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 210, in view_load
    load_from_oracle(view.file_name())
  File "/Users/simone/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 184, in load_from_oracle
    stderr=subprocess.PIPE, shell=shell)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'elm-oracle'
```

I've installed elm-oracle with `npm install -g elm-oracle` and it's in my `$PATH`:

```
$ which elm-oracle
/Users/simone/.nvm/versions/node/v5.1.0/bin/elm-oracle
$ echo $PATH
/Users/simone/.nvm/versions/node/v5.1.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

Any idea why this would happen or how I can fix it?

**Comment by ajhager** [comment]
I just want to make sure you have added the full path to elm-oracle to "elm_paths" in your config like it suggests in the README?

"Add the absolute path of the directory containing elm-format to the elm_paths setting in your Elm Language Support User settings."

 If that doesn't work, I can try to reproduce locally.

**Comment by simonewebdesign** [comment]
I've added it now, didn't add it in the first place because the README also says I can either add elm-oracle to PATH or edit the elm_paths setting.

It's working fine now, I'll let you know if I run into this issue again. Thanks!

**Comment by ajhager** [comment]
Glad it is working now. Happy coding!
