### ISSUE TITLE
Uncaught Error: No elm-oracle suggestions error indicated

### ISSUE THREAD

**Issue by kkruups** [ElmCast/elm-oracle#20]
[Enter steps to reproduce below:]
1. Occurred while typiing name of module in new source code file in Atom Editor
2. Typed:  module FunctionBasics  (Error occurred while typing name, first 2 or 3 characters)
    (note: autocomplete setting via atom-elm package (language-elm) is initiated autocomplete after two (2) characters).
   SEE Stack Trace Below

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.5.0
### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /C:/Users/22711973/.atom/packages/language-elm/lib/elmOracle.js:144

Error: No elm-oracle suggestions
    at parseOutput (C:/Users/22711973/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (C:/Users/22711973/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at ChildProcess.<anonymous> (C:/Users/22711973/.atom/packages/language-elm/lib/elmOracle.js:62:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
### Commands

```
  4x -4:47.1.0 window:increase-font-size (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:15 editor:newline (atom-text-editor.editor.is-focused)
     -4:13.3.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -4:12.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:12 core:move-left (atom-text-editor.editor.is-focused)
     -4:11.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:10.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:09.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:08.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:07.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -3:59.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:33.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:33.3.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "language-elm": {
    "elmOraclePath": "C:\\Users\\22711973\\AppData\\Roaming\\npm\\elm-oracle",
    "minCharsForAutocomplete": 2
  }
}
```
### Installed Packages

``` coffee
# User
atom-language-rust, v0.8.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
ink, v0.4.4
julia-client, v0.4.7
language-elm, v1.5.0
language-julia, v0.6.0
language-rust, v0.4.6
latex-completions, v0.3.1
linter, v1.11.14
linter-rust, v0.4.6
navigator-godef, v1.0.3
rust-api-docs-helper, v0.5.1
tester-go, v1.0.4
tool-bar, v1.0.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by tylerthehaas** [comment]
I also get this error in vim.  Mostly when I do it on Tuple functions.  Maybe Tuple needs to be added to things elm-oracle knows about?  To my understanding elm-oracle just looks at the documentation.json file inside the elm-stuff directory.  I have checked that file under the core directory and have found that Tuple exists.
